{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "f4dfe1ee-b394-4363-94a6-a8b5c23956ef",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2025-11-08 23:33:26.385 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-08 23:33:26.385 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-08 23:33:27.865 \n",
      "  \u001b[33m\u001b[1mWarning:\u001b[0m to view this Streamlit app on a browser, run it with the following\n",
      "  command:\n",
      "\n",
      "    streamlit run C:\\Users\\Aditya Rathod\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\ipykernel_launcher.py [ARGUMENTS]\n",
      "2025-11-08 23:33:27.869 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-08 23:33:27.871 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-08 23:33:27.871 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-08 23:33:27.874 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-08 23:33:27.874 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-08 23:33:27.888 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-08 23:33:27.888 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-08 23:33:27.892 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-08 23:33:27.895 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-08 23:33:27.896 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-08 23:33:27.898 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-08 23:33:27.900 Session state does not function when running a script without `streamlit run`\n",
      "2025-11-08 23:33:27.902 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-08 23:33:27.903 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-08 23:33:27.905 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-08 23:33:27.906 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-08 23:33:27.907 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-08 23:33:27.909 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-08 23:33:27.909 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-08 23:33:27.912 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-08 23:33:27.914 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-08 23:33:27.915 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-08 23:33:27.915 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-08 23:33:27.918 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-08 23:33:27.918 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-08 23:33:27.925 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-08 23:33:27.926 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-08 23:33:27.928 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-08 23:33:27.928 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-08 23:33:27.928 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-08 23:33:27.928 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-08 23:33:27.932 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-08 23:33:27.934 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-08 23:33:27.934 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-08 23:33:27.937 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-08 23:33:27.937 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-08 23:33:27.937 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-08 23:33:28.391 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-08 23:33:28.394 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-08 23:33:28.394 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n"
     ]
    }
   ],
   "source": [
    "import streamlit as st\n",
    "import pandas as pd\n",
    "import gspread\n",
    "from google.oauth2.service_account import Credentials\n",
    "from datetime import datetime\n",
    "\n",
    "# --- Google Sheet setup ---\n",
    "SHEET_NAME = \"Football_Ratings\"\n",
    "SCOPES = [\n",
    "    \"https://www.googleapis.com/auth/spreadsheets\",\n",
    "    \"https://www.googleapis.com/auth/drive\"\n",
    "]\n",
    "\n",
    "# Load credentials\n",
    "creds = Credentials.from_service_account_file(\"football-ratingsapp-e25de5e18c9b.json\", scopes=SCOPES)\n",
    "client = gspread.authorize(creds)\n",
    "sheet = client.open(\"Football Ratings spreadsheet\").sheet1\n",
    "\n",
    "# --- Streamlit UI ---\n",
    "st.set_page_config(page_title=\"Football Player Ratings\", page_icon=\"⚽\", layout=\"centered\")\n",
    "st.title(\"⚽ Daily Football Player Rating\")\n",
    "st.markdown(\"Rate your favourite player and see the live leaderboard below!\")\n",
    "\n",
    "# --- Input form ---\n",
    "with st.form(\"rating_form\"):\n",
    "    player = st.text_input(\"Enter Player Name:\")\n",
    "    rating = st.slider(\"Rate this player (1 to 10):\", 1, 10, 5)\n",
    "    reviewer = st.text_input(\"Your Name (optional):\")\n",
    "    submitted = st.form_submit_button(\"Submit Rating\")\n",
    "\n",
    "if submitted:\n",
    "    if player.strip():\n",
    "        date_today = datetime.today().strftime('%Y-%m-%d')\n",
    "        sheet.append_row([player, rating, reviewer, date_today])\n",
    "        st.success(f\"✅ Rating for *{player}* submitted successfully!\")\n",
    "    else:\n",
    "        st.error(\"Please enter a player name before submitting.\")\n",
    "\n",
    "# --- Leaderboard ---\n",
    "st.subheader(\"🏆 Live Leaderboard\")\n",
    "\n",
    "data = pd.DataFrame(sheet.get_all_records())\n",
    "if not data.empty:\n",
    "    leaderboard = (\n",
    "        data.groupby(\"Player\")[\"Rating\"]\n",
    "        .mean()\n",
    "        .reset_index()\n",
    "        .sort_values(by=\"Rating\", ascending=False)\n",
    "    )\n",
    "    leaderboard[\"Rating\"] = leaderboard[\"Rating\"].round(2)\n",
    "    st.dataframe(leaderboard, use_container_width=True)\n",
    "\n",
    "    st.bar_chart(leaderboard.set_index(\"Player\"))\n",
    "else:\n",
    "    st.info(\"No ratings yet. Be the first to rate!\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "95576c4f-fef5-485b-892c-6f33ebd6cda4",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.4"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
